@startuml
left to right direction
'scale 768 height
'scale 1366 width

title "Release Planning & Design"
skinparam class {
  BackgroundColor White
}
skinparam classBackgroundColor<<Change Case>> #CCDDFF
skinparam classBackgroundColor<<Tracer>> #FFDDCC
skinparam classBackgroundColor<<Architecture Subtask>> #FFDDCC
skinparam classBackgroundColor<<Test Case>> #FFDDCC
skinparam defaultFontSize 12

package "PRD Project" <<Frame>> {
  class "Feature" as prdepic << (P,#BB88BB) Epic >>
  class "User Story" as userstory << (P,#BB88BB) Story >>
  enum "Feature's\nFunctional\nRequirements" as prdreq << (P,#BB88BB) Filter >>
  (prdepic,userstory) ..o prdreq : aggregation
}


package "ARCH Project" <<Frame>> {
  class "Feature Design & Specification" as arch << (A,#4488BB) Architecture >>
  class "Technical\nAnalysis & Evaluation" as sysarch << (A,#4488BB) System Architecture >>
  class "Architecture\nChange/Improvement" as changecase << (A,#4488BB) Change Case >>
  class "Architecture\nAcceptance\nTest Case" as archtest << (A,#4488BB) Test Case >>
}

package "EUCA Project" <<Frame>> {
  class "Dev. Team Story" as devstory << (E,#22AA22) Story >>
  class "Technical Investigation" as archspike << (A,#4488BB) Spike >>
  class "Functional\nAcceptance\nTest Case" as prdtest << (P,#BB88BB) Test Case >>
  class "Development Task" as devtask << (E,#22AA22) Task>>
  class "Architecture Requirement" as archsubtask << (A,#4488BB) Architecture Subtask >>
  class "Sprint #1 Tracer" as archtracer << (A,#4488BB) Tracer >>

}

' prds to user stories
prdepic "1" *-- "*" userstory : composed of >
userstory "1" *-- "*" userstory : sub stories >

' arch work
prdepic "1" -- "*" arch : input to >
arch --> arch : refinement >
sysarch -- arch : calls for <
changecase ..> sysarch : becomes >

' Development Sprint & Planning
archspike *--> devtask : completed by <
devstory ..o prdreq : contributes to >
devtask *--> devstory   : completed by <
prdtest --> devstory : def. done >


' Sprint #1 Tracer
arch "1" --> "*" archspike : calls for >
sysarch "1" --> "*" archspike : calls for >
arch *--> archtracer : defines >
archtracer "1" o-> "*" prdtest
archtracer "1" *-> "*" archtest

' Continued evaluation throughout development
archsubtask "1" --> "1" devstory : def. done <
archtest --> archsubtask : def. done >


legend right
  <font color="#BB88BB">Product Management</font>
  <font color="#4488BB">Architecture</font>
  <font color="#22AA22">Development</font>
endlegend
hide methods
hide fields

@enduml
